### ISSUE TITLE
Retraining on NetMHCIIpan 4.0 data

### ISSUE THREAD

**Issue by prihoda** [pcpLiu/DeepSeqPanII#1]
Hi @pcpLiu, are you planning on retraining your model on the new NetMHCIIpan 4.0 dataset? http://www.cbs.dtu.dk/suppl/immunology/NAR_NetMHCpan_NetMHCIIpan/

**Comment by pcpLiu** [comment]
Hi @prihoda. Right now we don't have this plan.
