### ISSUE TITLE
about attention core 

### ISSUE THREAD

**Issue by zhangweizhenGitHub** [pcpLiu/DeepSeqPanII#2]
hi, pcpLiu,Thank you very much for your  this contribution.
 and I have some question to ask you:
1. I run python main.py "../Models/benchmark_weekly/model_bd2013.pytorch" "DRA*01:01" "DRB1*01:01" "AAYSDQATPLLLSPR"   output only is IC50 value  , This value is used to determine whether it can be presented. If the value is less than 0.5, it cannot be presented, and if it is greater than 0.5, it can be presented. Is that right?
2.  how can i get attention core ??

very thanks your help!!!!!!!!!

**Comment by pcpLiu** [comment]
1. Yeah. I remember that's the conventional threshold
2. The binding core weight is omitted here (https://github.com/pcpLiu/DeepSeqPanII/blob/master/code_and_dataset/main.py#L51)

**Comment by zhangweizhenGitHub** [comment]
Thank you very much for your quick reply！
I add  :pred_ic50, core = model() run again:
and The binding core weight is 1*25 tensor , As shown below
![image](https://user-images.githubusercontent.com/32630645/142127821-92e4e389-fed5-4714-b9a9-c9c6912391ea.png)
but the input sequence is "AAYSDQATPLLLSPR"  the length only 15 .

On this basis， how can i get  attention as shown below  👍 
![image](https://user-images.githubusercontent.com/32630645/142130858-87b00a53-192c-4e3a-87c0-a53e331583aa.png)
![image](https://user-images.githubusercontent.com/32630645/142130892-a4dd5e35-618b-454e-94d2-15cd28a84b7f.png)

i use the core output tensor to list:
![image](https://user-images.githubusercontent.com/32630645/142131334-ff00afd6-03ac-476f-9844-4c965115e3fb.png)

but finally,attencore's length is 17 and != "AAYSDQATPLLLSPR"(15)

so Is it something I didn't consider？？

**Comment by zhangweizhenGitHub** [comment]
> 2. The binding core weight is omitted here (https://github.com/pcpLiu/DeepSeqPanII/blob/master/code_and_dataset/main.py#L51)
i think this is due to padding, so I delete list1 to new list1 👍 
![image](https://user-images.githubusercontent.com/32630645/142143633-b5257425-87d5-4c9e-b33a-71db7f41a2c9.png)

and i can use 0.46840000000000004 ' s index to find out "attention core", Is that right?

**Comment by pcpLiu** [comment]
@zhangweizhenGitHub  right. when you are sliding the core window (9-length), in our paper, we select the window with max sum weights

**Comment by zhangweizhenGitHub** [comment]
> @zhangweizhenGitHub right. when you are sliding the core window (9-length), in our paper, we select the window with max sum weights

yeah,thank you for your help!
